### ISSUE TITLE
Onboarding Quests

### ISSUE THREAD

**Issue by jooshwelsh** [calabara-hq/calabara#11]
### New Feature

Customizable quest builder to fit the onboarding needs of a that specific DAO. 

Problem: Potential members and newbies to web3 have a hard time figuring out how to join, the organizational flows, and how to contribute. 
Solution Statement: Tools to help people onboard and start contributing to the DAO or web3 community.

### How could we do it?

Have a customizable quest builder where admins can build their own quests into their onboarding process.

### Screenshots & Files

https://rabbithole.gg/

^ rabbit hole is an example of quests

**Comment by ndodson** [comment]
What are onboarding quests? In my mind they are more immersive onboarding activities that help bring new members up to speed, help potential members learn about the DAO, and funnel members into ongoing works and tasks in the DAO based on their interests

We have been talking about this stuff for a couple weeks now with @hatsauce leading the idea

How would this look on the platform as a new feature? One idea is to build a modular design tool that gives DAO leaders/onboarding leads some degrees of freedom in designing and hosting more immersive onboarding activities via an app in Calabara.

At a high level, I think these onboarding activities can be broken into 3 different categories:

1. I'm new to crypto/DAO's. How do I get started?

2. What does this community do? How do key parts function? (think tokenomics, governance, contributing, etc)

3. I'm interested in X, is there anything I can do to apply/refine these skills that will potentially surface as a relevant contribution to an ongoing project in the DAO?

**Comment by ndodson** [comment]
https://www.figma.com/file/WRRjx1O47x39O9CVgsZYrV/Onboarding-App-Jam?node-id=0%3A1
